# Import function that generates interview questions using LLM
from llm import generate_interview_questions

# Import function that inserts questions into SQLite database
from database import insert_question

# Import function that saves questions into JSON file
from json_manager import save_to_json

# prints application heading
print("=" * 50)
print("AI Interview Question Repository")
print("=" * 50)

subject = input("\nEnter Subject or Topic: ").strip()       # Ask user to enter topic

data = generate_interview_questions(subject)       

# extracts only list of questions
questions = data["questions"]

# Stores only newly added questions
new_questions = []

print("\nTop 50 Interview Questions\n")

# Loop through all generated questions
# enumerate() gives both index and question
for i, question in enumerate(questions, start=1):

    print(f"{i}. {question}")           # Display every question to the user

   # Try to insert the question into database 
    inserted = insert_question(
        subject,
        question,
        "LLM"
    )

    if inserted:                         # If the question is new, store it in the list
        new_questions.append(question)

# Save only new questions to JSON
if new_questions:
    save_to_json({
        "subject": subject,
        "questions": new_questions
    })


# Display summary information
print("\n" + "=" * 50)
print(f"Displayed Questions : {len(questions)}")        # Total questions generated by the LLM
print(f"New Questions Saved : {len(new_questions)}")    # Number of newly inserted questions

# Number of questions that already existed
print(                                                
    f"Already Existing     : "
    f"{len(questions) - len(new_questions)}"
)
print("=" * 50)